import Accodian from "@/components/digitalAgency/accordian/Accodian";
import Box from "@/components/digitalAgency/crafting-steps/Box";
import ServicesBanner from "@/components/digitalAgency/services-banner/ServicesBanner";
import Steps from "@/components/digitalAgency/steps/Steps";
import WireFrame from "@/components/digitalAgency/wireframe/WireFrame";
import Head from "next/head";
import { useRouter } from "next/router";
import data from "../../../../data/sub-services.json";
 

const digitalAgency = () => {
const { query } = useRouter();
const skill = data.tele_communication.find((s: any) => s.slug === query.skill);

 
  return (
   <>
    <Head>
        <title>{skill?.hero_section.main_heading}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/leilani_favicon.ico" />
      </Head>
      <main>
      <ServicesBanner skill={skill?.hero_section}/>
        <Box data={skill} />
        <Steps data={skill} />
        <WireFrame data={skill} />
        {/* <Accodian /> */}
      </main>
   </>
  )
}

export default digitalAgency;