import Head from "next/head";
import Banner from "@/components/global/banner/Banner";
import Hero from "@/components/global/hero/Hero";
import OutStory from "@/components/home/out-story/OutStory";
import Telecom from "@/components/home/telecommunication/Telecom";
import SofwareDevelopment from "@/components/global/software-development/SofwareDevelopment";
import Team from "@/components/home/team/Team";
import ChooseUs from "@/components/home/choose-us/ChooseUs";
import Portfolio from "@/components/home/portfolio/Portfolio";
import ClinetsFeatures from "@/components/services/clients-featured/ClinetsFeatures";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/leilani_favicon.ico" />
      </Head>
      <main>
        <Banner />
        <Hero />
        <OutStory />
        <Telecom />
        <SofwareDevelopment />
        <ChooseUs />
        <Team />
        <Portfolio />
        <div style={{marginTop:'5%'}}>
          <ClinetsFeatures />
        </div>
        
      </main>
    </>
  );
}
