import Blog from "@/components/blogs/blogs/Blog";
import Journal from "@/components/blogs/journal/Journal";
import Pagination from "@/components/blogs/pagination/Pagination";
import Head from "next/head";
import { useState, useEffect } from "react";

const LIMIT_PER_PAGE = 6;

const blogs = (data: any) => {
  const TOTAL_BLOGS = data.results;
  const [loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState<any>(1);
  const [allBlogs, setAllBlogs] = useState([]);
  console.log(data);

  const totalPages = Math.ceil(TOTAL_BLOGS / LIMIT_PER_PAGE);

  const handleClick = (pageNumber: any) => {
    setCurrentPage(pageNumber);
    setLoading(true);
  };
  useEffect(() => {
    if (currentPage != 1) {
      fetch(
        `https://leilani-blogs.vercel.app/blog?limit=${LIMIT_PER_PAGE}&page=${currentPage}`,
        {
          method: "GET",
        }
      )
        .then((data) => {
          return data.json();
        })
        .then((blogs) => {
          setAllBlogs(blogs);
        });
    } else {
      setAllBlogs([]);
    }
  }, [currentPage]);

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/leilani_favicon.ico" />
      </Head>
      <main>
        <Journal />
        <Blog allBlogs={allBlogs.length < 1 ? data.data : allBlogs} />
        {TOTAL_BLOGS < LIMIT_PER_PAGE ? (
          <>
            <Pagination
              totalPages={totalPages}
              currentPage={currentPage}
              handleClick={handleClick}
            />
          </>
        ) : null}
      </main>
    </>
  );
};

export default blogs;

export const getStaticProps = async () => {
  const res = await fetch(
    `https://leilani-blogs.vercel.app/blog?limit=${LIMIT_PER_PAGE}`
  );
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};
